### ISSUE TITLE
/bin/sh: adb: command not found

### ISSUE THREAD

**Issue by GrishinSergey** [extmkv/ADB-Wifi#9]
Hello, I'm trying to run this tool on my mac. I ran command like this: `~ % adb-wifi` but this tools just shows message with some period:
`/bin/sh: adb: command not found`.
I connected device and permit to install apps to it from android studio. Then disconnected device from macbook and device disappeared from list of available devices for install apps. What I'm doing wrong?

**Comment by extmkv** [comment]
Make sure you've the adb installed and added to PATH in your system
